// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaAvonale.Data;

#nullable disable

namespace ProvaAvonale.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220518173340_criadoOMapeamento")]
    partial class criadoOMapeamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-preview.4.22229.2");

            modelBuilder.Entity("ProvaAvonale.Models.ProdutoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataUltimaVenda")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DataUltimaVenda");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Nome");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Quantidade");

                    b.Property<double>("ValorUltimaVenda")
                        .HasColumnType("DOUBLE")
                        .HasColumnName("ValorUltimaVenda");

                    b.Property<double>("ValorUnitario")
                        .HasColumnType("DOUBLE")
                        .HasColumnName("ValorUnitario");

                    b.HasKey("Id");

                    b.ToTable("Produto", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
